import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import NavBar from "./NavBar";
import "./styles/NavbarStyles.css";
import PreloadEffect from "./PreloadEffect";
import "./Preload.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Task Manager",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} preload`}>
        
        <NavBar />
        
        {children}
        
      </body>
      <PreloadEffect />
    </html>
  );
}
